<?php

namespace Customize\Twig\Extension;

use Eccube\Common\EccubeConfig;
use Eccube\Repository\CategoryRepository;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * CategoryExtension
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryExtension extends AbstractExtension
{
    /**
     * @var EccubeConfig
     */
    protected $eccubeConfig;

    /**
     * @var CategoryRepository
     */
    protected $categoryRepository;

    /**
     * NewProductExtension constructor.
     *
     * @param EccubeConfig $eccubeConfig
     * @param ProductRepository $productRepository
     */
    public function __construct(
        EccubeConfig $eccubeConfig,
        CategoryRepository $categoryRepository
    ) {
        $this->eccubeConfig = $eccubeConfig;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Returns a list of functions to add to the existing list.
     *
     * @return TwigFunction[] An array of functions
     */
    public function getFunctions()
    {
        return [
            new TwigFunction('category_by_id', [$this, 'getCategoryById']),
            new TwigFunction('is_treat_menu', [$this, 'isTreatMenu']),
            new TwigFunction('child_category_by_id', [$this, 'getChildCategoryById']),
        ];
    }

    public function getCategoryById($id)
    {
        if ($id) {
          $TargetCategory = $this->categoryRepository->find($id);
          if (!$TargetCategory) {
              throw new NotFoundHttpException();
          }
        } else {
          throw new NotFoundHttpException();
        }

        $Products = [];

        if ($TargetCategory->hasProductCategories()) {
          $ProductCategories = $TargetCategory->getProductCategories();
          foreach ($ProductCategories as $ProductCategory) {
            $Product = $ProductCategory->getProduct();
            if ($Product->isEnable()) {
                $Products[] = $Product;
            }
          }
        }

        return $Products;
    }

    public function isTreatMenu($id = null)
    {
        if ($id) {
          $TargetCategory = $this->categoryRepository->find($id);
          if (!$TargetCategory) {
              return false;
          }
        } else {
            return false;
        }

        $treatment_menu_id = $this->eccubeConfig['custom.category.treatment_menu_id'];

        // 施術メニューである
        if ($TargetCategory->getId() == $treatment_menu_id) {
            return true;
        }

        $Parents = $TargetCategory->getParents();

        // 施術メニューでもないし、親カテゴリもない
        if (count($Parents) == 0) {
            return false;
        }

        foreach ($Parents as $Parent) {
            // 施術メニューではないが、親カテゴリが施術メニュー
            if ($Parent->getId() == $treatment_menu_id) {
                return true;
            }
        }

        return false;
    }    

    public function getChildCategoryById($id)
    {
        if ($id) {
          $TargetCategory = $this->categoryRepository->find($id);
          if (!$TargetCategory) {
              throw new NotFoundHttpException();
          }
        } else {
          throw new NotFoundHttpException();
        }

        $Categories = [];

        $Children = $TargetCategory->getChildren();

        return $Children;
    }
}